words = {
	"Stajer":"Stajyer",
	"Espiri":"Espri",
	"Ünvan":"Unvan",
	"Haftasonu":"Hafta Sonu",
	"Haftaiçi":"Hafta İçi",
	"Şevkât":"Şefkat",
	"Hoşgeldin":"Hoş Geldin",
	"Çörekotu":"Çörek Otu",
	"Yada":"Ya Da",
	"Önsöz":"Ön Söz",
	"Semiz Otu":"Semizotu",
	"Makina":"Makine",
	"Maydonoz":"Maydanoz",
	"Mönü":"Menü",
	"Vejetaryan":"Vejetaryen",
	"Meyva":"Meyve",
	"Pardesü":"Pardösü",
	"Şarz":"Şarj",
	"Kirbit":"Kibrit",
	"Dinazor":"Dinozor",
	"Yanlız":"Yalnız",
	"Klavuz":"Kılavuz",
	"Bir kaç":"Birkaç",
	"Kiprik":"Kirpik",
	"Peşpeşe":"Peş Peşe",
	"Hiç bir":"Hiçbir",
	"İnsiyatif":"İnisiyatif",
	"Döküman":"Doküman",
	"Antreman":"Antrenman",
	"Ardarda":"Art Arda",
	"Laboratuar":"Laboratuvar",
	"Restorant":"Restoran",
	"Fantazi":"Fantezi",
	"Kurdela":"Kurdele",
	"Herkez":"Herkes",
	"Laylon":"Naylon",
	"Eşortman":"Eşofman",
	"Karnıbahar":"Karnabahar",
	"Terketmek":"Terk Etmek",
	"Traş":"Tıraş",
	"Orjinal":"Orijinal",
	"Hoşçakal":"Hoşça Kal",
	"Ana Okulu":"Anaokulu",
	"Git Gide":"Gitgide",
	"Herşey":"Her Şey",
	"Rüzgar":"Rüzgâr",
	"Yalnış":"Yanlış",
	"Birgün":"Bir gün",
	"Birşey":"Bir şey",
	"Pekçok":"Pek çok",
	"Pekaz":"Pek az",
	"Arasıra":"Ara sıra",
	"Yanısıra":"Yanı sıra",
	"Peşisıra":"Peşi sıra",
	"Ardısıra":"Ardı sıra",
	"Akşam üstü":"Akşamüstü",
	"Ayak üstü":"Ayaküstü",
	"Suç üstü":"Suçüstü",
	"Vaz geçmek":"Vazgeçmek",
	"Baş vurmak":"Başvurmak",
	"Haketmek":"Hak etmek",
	"Ön görmek":"Öngörmek",
	"Karma karışık":"Karmakarışık",
	"Rastgelmek":"Rast gelmek",
	"Vurdum duymaz":"Vurdumduymaz",
	"Ve ya":"Veya",
	"Yada":"Ya da",
	"Yalnış":"Yanlış",
	"Yanlız":"Yalnız",
	"Kiprik":"Kirpik",
	"Kirbit":"Kibrit",
	"Pehriz":"Perhiz",
	"Pisikoljk":"Psikolojik",
	"Orjinal":"Orijinal",
	"Klavuz":"Kılavuz",
	"Ropörtaj":"Röportaj",
	"İnsiyatif":"İnisiyatif",
	"Mataryal":"Materyal",
	"Antreman":"Antrenman",
	"Eşortman":"Eşofman",
	"Çenber":"Çember",
	"Makina":"Makine",
	"Matba":"Matbaa",
	"Zatüre":"Zatürre",
	"Deynek":"Değnek",
	"Süpriz":"Sürpriz",
	"Poaça":"Poğaça",
	"Sandoviç":"Sandviç",
	"Pilaj":"Plaj",
	"Traş":"Tıraş",
	"Şöför":"Şoför",
	"Metod":"Metot",
	"Komser":"Komiser",
	"Afaroz":"Aforoz",
	"Izdırap":"Istırap",
	"Fantazi":"Fantezi",
	"Espiri":"Espri",
	"Kavonoz":"Kavanoz",
	"Parentez":"Parantez",
	"Fülüt":"Flüt",
	"Beyzbol":"Beysbol",
	"Entellektüel":"Entelektüel",
	"Kollektif":"Kolektif",
	"Dinazor":"Dinozor",
	"Kontür":"Kontör",
	"Silahşör":"Silahşor",
	"Tesbit":"Tespit",
	"Karnıbahar":"Karnabahar",
	"Kapütülasyon":"Kapitülasyon",
	"Kıravat":"Kravat",
	"Patetes":"Patates",
	"Sağol":"Sağ Ol",
	"Aperatif":"Aperitif",
	"Telafuz":"Telaffuz",
	"Hopörlör":"Hoparlör",

	"ahçı":"aşçı",
	"ahpap":"ahbap",
	"aliminyum":"alüminyum",
	"anotomi":"anatomi",
	"antreman":"antrenman",
	"arabeks":"arabesk",
	"ardarda":"art arda",
	"ateşe":"ataşe",
	"baya":"bayağı",
	"canbaz":"cambaz",
	"cimnastik":"jimnastik",
	"dekarasyon":"dekorasyon",
	"dekaratör":"dekoratör",
	"deyinmek":"değinmek",
	"dinazor":"dinozor",
	"döküman":"doküman",
	"entellektüel":"entelektüel",
	"entrasan":"enteresan",
	"erezyon":"erozyon",
	"espiri":"espri",
	"eşortman":"eşofman",
	"eşşek":"eşek",
	"eylenmek":"eğlenmek",
	"fasülye":"fasulye",
	"florasan":"floresan",
	"gardolap":"gardırop",
	"halisinasyon":"halüsinasyon",
	"herkez":"herkes",
	"Hıristiyan":"Hristiyan",
	"Hintli":"Hint",
	"hoporlör":"hoparlör",
	"ıstırap":"ızdırap",
	"inkilap":"inkılap",
	"insiyatif":"inisiyatif",
	"iskan":"iskân",
	"izalasyon":"izolasyon",
	"kağıt":"kâğıt",
	"kalemşör":"kalemşor",
	"karekter":"karakter",
	"karemel":"karamel",
	"karnıbahar":"karnabahar",
	"kavonoz":"kavanoz",
	
	"kilot":"külot",
	"kipri":"kirpi",
	"kiprik":"kirpik",
	"kirbit":"kibrit",
	"kitlemek":"kilitlemek",
	"klavuz":"kılavuz",
	"kokreç":"kokoreç",
	"kolanya":"kolonya",
	"kollej":"kolej",
	"kolleksiyon":"koleksiyon",
	"kollektif":"kolektif",
	"komidin":"komodin",
	"kominist":"komünist",
	"komünükasyon":"komünikasyon",
	"konsansüs":"konsensüs",
	"kontür":"kontör",
	"kopye":"kopya",
	"korkunç güzel":"çok güzel",
	"kozmatik":"kozmetik",
	"kurdela":"kurdele",
	"küpür":"kupür",
	"küvöz":"kuvöz",
	"labaratuar":"laboratuvar",
	"lağbo":"lavabo",
	"laylon":"naylon",
	"leyen":"leğen",
	"logar":"rögar",
	"mağma":"magma",
	"mahçup":"mahcup",
	"mahsuz":"mahsus",
	"makina":"makine",
	"maktül":"maktul",
	"manüpülasyon":"manipülasyon",
	"matamatik":"matematik",
	"maydonoz":"maydanoz",
	"mazohist":"mazoşist",
	"mazohizm":"mazoşizm",
	"megoloman":"megaloman",
	"mekânizma":"mekanizma",
	"melemen":"menemen",
	"menapoz":"menopoz",
	"menejer":"menajer",
	"mentalite":"mantalite",
	"menüsküs":"menisküs",
	"meraba":"merhaba",
	"meslekdaş":"meslektaş",
	"mevlüt":"mevlut",
	"meyva":"meyve",
	"-mişli geçmiş":"belirsiz geçmiş",
	"mokasen":"makosen",
	"motorsiklet":"motosiklet",
	"mozayik":"mozaik",
	"mönü":"menü",
	"muaffak":"muvaffak",
	"mütahit":"müteahhit",
	"nisbet":"nispet",
	"oparasyon":"operasyon",
	"orjinal":"orijinal",
	"ötenazi":"ötanazi",
	"palyanço":"palyaço",
	"panaroma":"panorama",
	"panik oldum":"panik olmak",
	"pantalon":"pantolon",
	"parağraf":"paragraf",
	"pardesü":"pardösü",
	"parelel":"paralel",
	"parende":"perende",
	"parlementer":"parlamenter",
	"parlemento":"parlamento",
	"penbe":"pembe",
	"personeller":"personel",
	"peştemal":"peştamal",
	"pisiklet":"bisiklet",
	"poaça":"poğaça",
	"profütür":"profiterol",
	"proğram":"program",
	"proleterya":"proletarya",
	"promasyon":"promosyon",
	"provakatör":"provokatör",
	"psikiyatrist":"psikiyatr",
	"püsküüt":"bisküvi",
	"radyosyon":"radyasyon",
	"rakkam":"rakam",
	"restorant":"restoran",
	"revanş":"rövanş",
	"rezarvasyon":"rezervasyon",
	"riks":"risk",
	"romörkör":"römorkör",
	"sağnak":"sağanak",
	"sahne almak":"sahneye çıkmak",
	"salomanje":"salamanje",
	"sandoviç":"sandviç",
	"santranç":"satranç",
	"sarmısak":"sarımsak",
	"satlık":"satılık",
	"senle":"seninle",
	"seramoni":"seremoni",
	"serbes":"serbest",
	"seyehat":"seyahat",
	"sezeryan":"sezaryen",
	"Sıvas":"Sivas",
	"sigara kullanmak":"sigara içmek",
	"silahşör":"silahşor",
	"siluet":"silüet",
	"sitriptiz":"striptiz",
	"sohpet":"sohbet",
	"sollama yapmak":"sollamak",
	"sovan":"soğan",
	"soy kırımı":"soykırım",
	"statyum":"stadyum",
	"steteskop":"stetoskop",
	"su basmanı":"subasman",
	"subap":"supap",
	"sueter":"süveter",
	"südyen":"sütyen",
	"sükûtuhayal":"sukutuhayal",
	"süpriz":"sürpriz",
	"sütüdyo":"stüdyo",
	"şanzuman":"şanzıman",
	"şarter":"şalter",
	"şarz":"şarj",
	"şemşiye":"şemsiye",
	"şevkat":"şefkat",
	"şifai":"şifahi",
	"şindi":"şimdi",
	"şohben":"şofben",
	"şok olmak":"şoke olmak",
	"şöför":"şoför",
	"taamüden":"taammüden",
	"tafsiye":"tavsiye",
	"tahtarevalli":"tahterevalli",
	"takikardi":"taşikardi",
	"tanımamazlık":"tanımazlık",
	"tanpon":"tampon",
	"tasfir":"tasvir",
	"tasviye":"tasfiye",
	"taşaron":"taşeron",
	"teferuat":"teferruat",
	"tenbel":"tembel",
	"tenbih":"tembih",
	"tenefüs":"teneffüs",
	"tesbih":"tespih",
	"tesbit":"tespit",
	"teşebüs":"teşebbüs",
	"teşfik":"teşvik",
	"tetanoz":"tetanos",
	"tiskinmek":"tiksinmek",
	"tolorans":"tolerans",
	"traş":"tıraş",
	"tükrük":"tükürük",
	"usül":"usul",
	"ünvan":"unvan",
	"üvertür":"uvertür",
	"valeybol":"voleybol",
	"variyetli":"zengin",
	"vejeteryan":"vejetaryen",
	"yanlız":"yalnız",
	"yayınlamak":"yayımlamak",
	"Yunanlı":"Yunan"
}